export enum StatusType {
  CREATED = "CREATED",
  DONE = "DONE",
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  MODIFIED = "MODIFIED",
  APPROVED = "APPROVED",
  TERMINATED = "TERMINATED",
  CANCELLED = "CANCELLED",
}
